#include "editor/level_editor/level_panel.h"

#include "absl/status/status.h"
#include "common/status_macros.h"
#include "editor/gui_interface.h"
#include "editor/imgui_scoped.h"
#include "imgui.h"
#include "objects/level.h"

namespace zebes {

constexpr char kAutoGenerated[] = "<auto>";

absl::StatusOr<std::unique_ptr<LevelPanel>> LevelPanel::Create(Options options) {
  if (options.api == nullptr) {
    return absl::InvalidArgumentError("API can not be null.");
  }
  if (options.gui == nullptr) {
    return absl::InvalidArgumentError("Gui can not be null.");
  }
  return absl::WrapUnique(new LevelPanel(std::move(options)));
}

LevelPanel::LevelPanel(Options options) : api_(*options.api), gui_(options.gui) {
  RefreshLevelCache();
}

absl::StatusOr<LevelResult> LevelPanel::Render(std::optional<Level>& level) {
  ScopedId id(gui_, "LevelPanel");

  gui_->Text("Levels");
  gui_->Separator();

  if (level.has_value()) {
    return RenderDetails(level);
  }

  return RenderList(level);
}

absl::StatusOr<LevelResult> LevelPanel::RenderList(std::optional<Level>& level) {
  LevelResult result;

  if (gui_->Button("Create")) {
    ASSIGN_OR_RETURN(result, HandleOp(level, Op::kLevelCreate));
  }
  gui_->SameLine();

  if (gui_->Button("Edit")) {
    ASSIGN_OR_RETURN(result, HandleOp(level, Op::kLevelEdit));
  }
  gui_->SameLine();

  {
    ScopedStyleColor style(gui_, ImGuiCol_Button, ImVec4(0.8f, 0.2f, 0.2f, 1.0f));
    if (gui_->Button("Delete")) {
      ASSIGN_OR_RETURN(result, HandleOp(level, Op::kLevelDelete));
    }
  }

  if (ScopedListBox list_box(gui_, "##Levels", ImVec2(-FLT_MIN, -FLT_MIN)); list_box) {
    for (int i = 0; i < level_cache_.size(); ++i) {
      const bool is_selected = (selected_index_ == i);
      if (gui_->Selectable(level_cache_[i].name.c_str(), is_selected)) {
        selected_index_ = i;
      }

      // Set the initial focus when opening the combo (scrolling + keyboard navigation focus)
      if (is_selected) gui_->SetItemDefaultFocus();
    }
  }

  return result;
}

absl::StatusOr<LevelResult> LevelPanel::RenderDetails(std::optional<Level>& level) {
  LevelResult result;
  // At this point we known that level is not null.
  Level& lvl = *level;

  if (gui_->Button("Back")) {
    ASSIGN_OR_RETURN(result, HandleOp(level, Op::kLevelBack));
  }

  gui_->SameLine();
  if (gui_->Button("Save")) {
    ASSIGN_OR_RETURN(result, HandleOp(level, Op::kLevelSave));
  }

  gui_->Separator();
  gui_->Text("Details");

  gui_->InputText("ID", &lvl.id, ImGuiInputTextFlags_ReadOnly);
  gui_->InputText("Name", &lvl.name);
  gui_->InputDouble("Width", &lvl.width);
  gui_->InputDouble("Height", &lvl.height);

  gui_->Text("Spawn Point");
  gui_->InputDouble("X", &lvl.spawn_point.x);
  gui_->SameLine();
  gui_->InputDouble("Y", &lvl.spawn_point.y);

  return result;
}

absl::StatusOr<LevelResult> LevelPanel::HandleOp(std::optional<Level>& level, Op op) {
  LevelResult result;

  if (op == Op::kLevelEdit || op == Op::kLevelDelete) {
    if (level.has_value()) {
      return absl::InvalidArgumentError("Level must be null!");
    }
    if (selected_index_ < 0) {
      LOG(INFO) << "No level selected, not deleting...";
      return result;
    }
    if (selected_index_ >= level_cache_.size()) {
      return absl::InternalError("Selected index outside of range!!!");
    }
  }

  switch (op) {
    case Op::kLevelCreate: {
      ++counters_.create;
      level = Level{.id = kAutoGenerated, .name = "name"};
      ASSIGN_OR_RETURN(std::string id, api_.CreateLevel(*level));
      level->id = id;
      level_cache_.push_back(*level);
      result.type = LevelResult::kChanged;
      break;
    }
    case Op::kLevelEdit:
      ++counters_.edit;
      level = level_cache_[selected_index_];
      result.type = LevelResult::kChanged;
      break;
    case Op::kLevelSave:
      ++counters_.save;
      if (!level.has_value()) {
        return absl::InvalidArgumentError("Level must not be null!");
      }
      RETURN_IF_ERROR(api_.UpdateLevel(*level));
      RefreshLevelCache();
      result.type = LevelResult::kChanged;
      break;
    case Op::kLevelDelete:
      ++counters_.del;
      RETURN_IF_ERROR(api_.DeleteLevel(level_cache_[selected_index_].id));
      RefreshLevelCache();
      result.type = LevelResult::kChanged;
      break;
    case Op::kLevelBack:
      ++counters_.back;
      level.reset();
      result.type = LevelResult::kChanged;
      break;
  }

  return result;
}

void LevelPanel::RefreshLevelCache() {
  level_cache_ = api_.GetAllLevels();

  std::sort(level_cache_.begin(), level_cache_.end(),
            [](const Level& a, const Level& b) { return a.name < b.name; });

  LOG(INFO) << "Loaded " << level_cache_.size() << " levels.";
}

}  // namespace zebes
