#!/usr/bin/env python3
"""Generate .claude/rules/*.md from the marked sections of docs/style-guide.md.

The style guide is the source of truth. Claude Code cannot read it directly on
demand, so the normative sections are extracted into `.claude/rules/`, where
they load automatically when someone edits a matching file. This script does the
extraction; `--check` fails when the generated files no longer match the guide,
which is how the copies are kept from drifting apart.

Mark a section in the guide with a pair of HTML comments:

    <!-- rule:cpp-style paths="**/*.cc,**/*.h" -->
    ## C++ style
    ...
    <!-- /rule -->

Everything between them becomes `.claude/rules/cpp-style.md`. A rule may have
several blocks in the guide; they are concatenated in the order they appear, and
only the first needs the `paths` attribute. Omit `paths` entirely and the rule
loads in every session instead of only for matching files.

Usage:
    scripts/sync_rules.py            # write the rule files
    scripts/sync_rules.py --check    # exit 1 if they are stale
"""

import argparse
import re
import sys
from pathlib import Path

GUIDE_RELATIVE_PATH = Path("docs") / "style-guide.md"
RULES_RELATIVE_PATH = Path(".claude") / "rules"

BANNER = (
    "<!-- Generated by scripts/sync_rules.py from docs/style-guide.md.\n"
    "     Do not edit this file. Edit the style guide and rerun the script. -->"
)

OPEN_MARKER = re.compile(
    r'^<!--\s*rule:(?P<name>[a-z0-9][a-z0-9-]*)'
    r'(?:\s+paths="(?P<paths>[^"]*)")?\s*-->\s*$'
)
CLOSE_MARKER = re.compile(r"^<!--\s*/rule\s*-->\s*$")
FENCE = re.compile(r"^\s*(?:```|~~~)")
HEADING = re.compile(r"^(#{1,6})\s+\S")


class GuideError(Exception):
    """The guide's rule markers are malformed. Reported without a traceback."""


class Rule:
    def __init__(self, name, paths, line_number):
        self.name = name
        self.paths = paths
        self.line_number = line_number
        self.blocks = []


def parse_guide(text):
    """Return the rules marked up in the guide, in the order they first appear."""
    rules = {}
    order = []
    open_rule = None
    open_line = 0
    body = []
    in_fence = False

    for line_number, line in enumerate(text.splitlines(), start=1):
        # A marker inside a fenced code block is documentation, not markup. The
        # usage example in this script's own docstring is why that matters.
        if FENCE.match(line):
            in_fence = not in_fence
            if open_rule is not None:
                body.append(line)
            continue

        if not in_fence:
            opened = OPEN_MARKER.match(line)
            if opened:
                if open_rule is not None:
                    raise GuideError(
                        f"line {line_number}: rule:{opened.group('name')} opens "
                        f"while rule:{open_rule} is still open (line {open_line})"
                    )
                open_rule = opened.group("name")
                open_line = line_number
                body = []

                raw_paths = opened.group("paths")
                paths = (
                    [p.strip() for p in raw_paths.split(",") if p.strip()]
                    if raw_paths is not None
                    else []
                )
                if open_rule not in rules:
                    rules[open_rule] = Rule(open_rule, paths, line_number)
                    order.append(open_rule)
                elif paths and paths != rules[open_rule].paths:
                    raise GuideError(
                        f"line {line_number}: rule:{open_rule} declares paths that "
                        f"disagree with its first block (line "
                        f"{rules[open_rule].line_number}). Declare paths once."
                    )
                continue

            if CLOSE_MARKER.match(line):
                if open_rule is None:
                    raise GuideError(f"line {line_number}: /rule with no open rule")
                block = "\n".join(body).strip("\n")
                if not block:
                    raise GuideError(
                        f"line {open_line}: rule:{open_rule} block is empty"
                    )
                rules[open_rule].blocks.append(block)
                open_rule = None
                continue

        if open_rule is not None:
            body.append(line)

    if open_rule is not None:
        raise GuideError(f"line {open_line}: rule:{open_rule} is never closed")

    return [rules[name] for name in order]


def shift_headings(blocks):
    """Promote headings so the shallowest one in a rule becomes a top-level `#`.

    Sections are nested inside the guide but stand alone in a rule file, so a
    `##` in the guide should arrive as `#`. All blocks in a rule shift by the
    same amount to keep their relative depth.
    """
    depths = []
    for block in blocks:
        in_fence = False
        for line in block.splitlines():
            if FENCE.match(line):
                in_fence = not in_fence
                continue
            if in_fence:
                continue
            heading = HEADING.match(line)
            if heading:
                depths.append(len(heading.group(1)))
    if not depths:
        return blocks

    shift = min(depths) - 1
    if shift <= 0:
        return blocks

    shifted = []
    for block in blocks:
        in_fence = False
        lines = []
        for line in block.splitlines():
            if FENCE.match(line):
                in_fence = not in_fence
                lines.append(line)
                continue
            heading = HEADING.match(line)
            if heading and not in_fence:
                line = line[shift:]
            lines.append(line)
        shifted.append("\n".join(lines))
    return shifted


def render_rule(rule):
    parts = []
    if rule.paths:
        quoted = "\n".join(f'  - "{path}"' for path in rule.paths)
        parts.append(f"---\npaths:\n{quoted}\n---")
    parts.append(BANNER)
    parts.extend(shift_headings(rule.blocks))
    return "\n\n".join(parts) + "\n"


def generated_rule_files(rules_dir):
    """Existing rule files this script owns, identified by their banner."""
    if not rules_dir.is_dir():
        return []
    owned = []
    for path in sorted(rules_dir.rglob("*.md")):
        if BANNER.splitlines()[0] in path.read_text(encoding="utf-8"):
            owned.append(path)
    return owned


def sync(root, check):
    """Write or verify the rule files. Return a list of problems found."""
    guide_path = root / GUIDE_RELATIVE_PATH
    rules_dir = root / RULES_RELATIVE_PATH
    if not guide_path.is_file():
        raise GuideError(f"{GUIDE_RELATIVE_PATH} not found under {root}")

    rules = parse_guide(guide_path.read_text(encoding="utf-8"))
    if not rules:
        raise GuideError(f"{GUIDE_RELATIVE_PATH} marks no rule sections")

    expected = {rules_dir / f"{rule.name}.md": render_rule(rule) for rule in rules}
    stale = []

    for path, content in expected.items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == content:
            continue
        if check:
            stale.append(
                f"{path.relative_to(root)} is "
                f"{'missing' if current is None else 'out of date'}"
            )
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")

    # A rule file whose section left the guide would otherwise keep loading into
    # every session forever, which is the exact drift this script exists to stop.
    for path in generated_rule_files(rules_dir):
        if path in expected:
            continue
        if check:
            stale.append(
                f"{path.relative_to(root)} has no matching section in the guide"
            )
        else:
            path.unlink()

    return stale


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the rule files match the guide instead of rewriting them",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="repository root (defaults to the parent of scripts/)",
    )
    args = parser.parse_args(argv)

    try:
        stale = sync(args.root.resolve(), args.check)
    except GuideError as error:
        print(f"sync_rules: {error}", file=sys.stderr)
        return 2

    if stale:
        print("sync_rules: .claude/rules/ is out of sync with the style guide:",
              file=sys.stderr)
        for problem in stale:
            print(f"  {problem}", file=sys.stderr)
        print("Run scripts/sync_rules.py to regenerate.", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
